### ISSUE TITLE
[Feature Request] Extension for Notion

### ISSUE THREAD

**Issue by BoyangMichael** [raycast/script-commands#438]
Hello,

It would be really nice if you could consider making an official extension for Notion (like the ones for Github, G-Suite, etc), since now Notion's API is in already available in beta version. Thanks a lot!

First thing come to my mind is that an important feature of such extension would be the capability to search notion pages and open one of the results in browser or Notion app. Another useful feature would be to create a new entry in a specified notion database (good for logging or create todos).

I have thought about writing a script command, but it seems difficult because I don't know how to make the output show an interactive list of results. So I'm looking for the official's help! Thanks!

Thank you for considering this!

Kind regards,
Boyang

**Comment by PitNikola** [comment]
Hey @BoyangMichael! Thanks for the suggestion. Currently we're [heads down working on API](https://raycast.com/developer-program) so we haven't decided if we want to release Notion integration before that, but we'll consider.

I'm gonna close the issue here since it's not related to script-commands.
