### ISSUE TITLE
Applescript with emoji icon fail to run (continued)

### ISSUE THREAD

**Issue by sjregan** [raycast/script-commands#466]
This is a continuation of bug #55.

The default template created when adding a new AppleScript command includes the line:

`# @raycast.icon 🤖`

If you edit the script in ScriptEditor and then save, when executing the script via Raycast an error is shown:

`Script failed to run: The operation couldn't be completed. Exec format error.`

If you delete the raycast.icon line and save, the script runs as expected.

**Comment by grzegorzkrukowski** [comment]
Hey @sjregan the problem is that the AppleScript editor saves files as UTF-16LE when you add emoji to the file.
You can verify that with `file -I {filename}` command.
Once you remove the emoji and resave it - it goes back to UTF-8.

The best solution is to use a different editor than AppleScript editor where you can control encoding and make sure you are using UTF-8 always - that will make it work.

**Comment by sjregan** [comment]
Thanks for the response, good to know exactly how to deal with it.

If that's the case then my suggestion is to remove the emoji from the template as by default the script will open and run in the AppleScript editor but not in Raycast. Or support UTF-16LE in Raycast :)

**Comment by dehesa** [comment]
Hi @sjregan,

We will add support for UTF-16LE for apple scripts. It is already in the backlog and we will tackle this shortcoming soon.

Thank you for the feedback.
