### ISSUE TITLE
Proposal: make packageName required meta

### ISSUE THREAD

**Issue by crstauf** [raycast/script-commands#47]
If `packageName` was a required meta key, that allows for (at least) a couple things:

- increased portability of the script command (a user can cherry pick scripts outside of directories and not lose any context info)
- turn off entire packages rather than (or in addition to) individual scripts

While portability is important, I see the ability to turn off entire packages to be a critical step. For example, I use Cloudup as my screenshot sharing service, but there are plenty of other services that do that. A user of another service won't need Cloudup, and so would need to search the entire list for Cloudup scripts, or delete the files from their directory each time they update the scripts from this repository. If Raycast supported toggling entire packages, that'd be a one time change, and done.

I expect there are additional advantages to requiring `packageName`, whether now or in the future.

**Comment by maximkrouk** [comment]
Also, a package browser might be a nice feature if the proposal will be accepted. Maybe it's even worth making a fully package-based script import system instead of a folder-based (like in Xcode SPM with FolderURLs support).

**Comment by PitNikola** [comment]
Thanks for putting together this proposal @crstauf!

We had a discussion about this change and decided to not make `packageName` a required field. We actually had it required in our initial implementation, but then decided to make it less restrictive because in the end it's just a label in the list. It doesn't represent an ID, you can have script commands from different directories with same `packageName`, you can use it as a category and so on. Perhaps naming could've been better.

However, portability is indeed a good point, so we decided to make it a requirement to provide `packageName` for all scripts in this repository. I will add this section to the guidelines.

As to package based systems, it's deliberate decision to keep script commands as small, simple and self contained commands, so we want to avoid introducing complexity with any sort of package management. For more complex extensions there will be API.

Please let me know if you have any questions.
