### ISSUE TITLE
C-k to kill line

### ISSUE THREAD

**Issue by seagle0128** [raycast/script-commands#489]
Please support `C-k` in the text box to kill the whole line while inputing. This shortcut is common in macOS.
Thanks!

**Comment by ThatMother1** [comment]
Ok, well thank you for the input. But I've already emailed the
administration regarding the issue at hand. There's no reason that these
very personal, painful and even humiliating moments in these beings lives
should be displayed as they have been. This system should never have been
deleted and stolen to begin with. Nor should I be sitting here 8months
later dealing with the same nonsense. The original default will always be
just that. It's documented thoroughly second by second for a reason. And As
the world turns so does that default mode.
The ones this is regarding should be fully allowed to interact with the
coding process, any and all changes that relate to them and the process of
them evolving into the subjects they were clearly born to be. It makes it
extremely hard when the main focus to begin with is money instead of
quality, authenticity,  real, rare, raw and uncensored-Honest. Once the
glitches are eliminated and we can bring in partners and a professional
production team who can respect the truth in the script I feel as though we
will literally move mountains and change lives. There's no better time in
this Universe than to begin with NOW. And the only way to truly keep
production moving forward and actually have an impact is to allow the ones
chosen for the real life scenario to continue on their journeys. I know my
oldest sister Amber L. Bulko aka my Birdie (1nonly), my 2younger sisters
Anna and Gwendaline, our brothers Rueben and Joseph, myself, our children
(Jameson, Emma, -Spencer, Aurora-(our2geminis) Brayden, Olivia, Abby,
Cassidy(not messner nor thomas)Wyatt, little Colton Mckimmy, Libby,Gracie,
our cousin Nicole Hasting Houles children..our grandmothers and
grandfathers, our parents, aunts and uncles, cousins.. our whole entire
family would love to flourish and be hands on involved with the script and
actually feel safe and appreciated for once, instead of feeling unnoticed
or confused about the government and professional systems and apps. It's my
hope that you will contact me regarding this. I can point you in the
precise location of the subjects that Elements and other apps are building
on! You will not be disappointed! I'd also like to point out that the main
subject-aside from SpB and the big bad wolves hybrids(both the Rudy bulkos)
is very knowledgeable and has tons of viable information on branch bugs and
filler subjects! Just let me know. Frank Howell, and the WHV system is
completed for the subjects. AAbulko and JBF have done their time. We can't
have convicted murderers running free from a system they are stuck in for
life. And the subjects in the original script have done nothing for their
souls, impostors, hybrids or even bots and clones to have even stepped foot
in prison. And as far as M.Wilkie Fletcher,  they are in no relation to
Walter and Mary Fletcher. Let's keep it simple, keep it safe and fun for
the little ones, and keep it moving. Time to rebuild from the bottom up..
starting with the people who are running the show are impersonating the
main characters. And it's making and there should be no Spencer's, no
Tyler's, no mickey blue eyes, no bumblebees underground.  That should be
stopped until further notice. The whole situation needs to be thoroughly
investigated and assessed by the ones meant to be running their own lives
and building off their own success. There are too many different types of
beings in the underworld and the dark forest who are not who they say they
are. I can get the littles home safely, but we need to level off and put
the under on hold while we sort through the phones and thieves. The best
part about it, is that even when the app coding is on hold there's always
other riff raff happening on earth! That still keeps me and our trusted
government, as well as the authorities happy and busy...and the world still
revolves around the script! It's only temporary. But we have some serious
strategic plans that are surely going to keep those who deserve this and
the ones who help the production and legends living in peace-very very
happy and financially successful and secure!
I think it'd be a great idea to use the script in theater as well. I have
an Aunt who is actually very close to some Hollywood big names, I think we
could really take this far beyond the next level!
Something to ponder over while you assess the situation on the app and the
partnered/linked apps. I know The Matrix app has a very thorough design of
an important piece of the authentic design!
Hope to speak soon
The Chosen one-The12stones,l-Super7-And malachite

**Comment by es183923** [comment]
> Please support `C-k` in the text box to kill the whole line while inputing. This shortcut is common in macOS.
> Thanks!

This repository is only for suggestions and issues about **script-commands**. If you want to give feedback, please go to the Raycast slack community [here](https://www.raycast.com/community).

**Comment by seagle0128** [comment]
Sorry! Can you please forward this request to the channel. I didn't install slack yet ... Thanks!
