### ISSUE TITLE
Ability to set custom colors to `image-from-code.sh`

### ISSUE THREAD

**Issue by raveling** [raycast/script-commands#511]
Love this product! ✨ 🙇 

Do you have any plans to allow config of the color themes?
Would love to change the BG gradient (and syntax) to match a product I'm involved in.

Thanks for any help you can provide! 🙏 

https://github.com/raycast/script-commands/blob/master/commands/developer-utils/create-image-from-code.sh

**Comment by unnamedd** [comment]
Hey @raveling,

even though you are mentioning the Script Command [create-image-from-code.sh](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/create-image-from-code.sh), this issue is not related to something that could be done in a Script Command. For that reason, I'd like to kindly ask you to use the Send Feedback form available inside of Raycast:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/83694/125759961-0b53c7ae-b8e7-4251-b72f-9333e107aad7.png">

Or bring you suggestion to our community on Slack using the following URL: https://raycast.com/community

I'm going to close this issue, if you have any further question, please, let me know.

**Comment by raveling** [comment]
Thanks @unnamedd 🙏  will do
