### ISSUE TITLE
Is it possible to use arguments in inline ouput?

### ISSUE THREAD

**Issue by Jed-Z** [raycast/script-commands#512]
It seems that in "inline" output mode (`@raycast.mode inline`), arguments (`@raycast.argument1`) will be disabled.

**Comment by unnamedd** [comment]
You are right an this is the expected behaviour, as you can check in the official documentation, here:
https://github.com/raycast/script-commands/blob/master/documentation/OUTPUTMODES.md
and here:
https://github.com/raycast/script-commands/blob/master/documentation/ARGUMENTS.md

As this issue isn't related to any bug or anything actionable, I'm going to close this issue.
If you need anything else, please, let us know.

**Comment by remino** [comment]
I know this is an old issue and it is closed, but with the latest Raycast v1.51.1, I encountered the same issue and landed here. That said, I couldn't find anything in the documentation mentioning arguments are not accepted in inline mode, including on the pages linked above. Is there something missing?
