### ISSUE TITLE
[question] timeline for / support of embedded webview

### ISSUE THREAD

**Issue by ansaso** [raycast/script-commands#535]
Does raycast allow for scripts to pipe web-documents (alternatively urls) to be rendered in an embedded webview / fullOutput menu?

e.g. 
View rendered wikipedia page by piping the wikipedia url or the wikipedia html for that page.

---

I'm assuming not, since it would already be implemented for the native commands. 

If it's not yet supported - where is it on the roadmap?

---

For context I'm checking the feasibility of adding flashcards to anki more dynamically. It's looks like it's strictly possible without a webview, but I'd have to convert exceedingly large html files to a raycast readable output - which I'm probably not going to do.

**Comment by dehesa** [comment]
Hey @ansaso,

That is a good question. Currently we don't support rendering that type of view (neither embedded webview nor canvas or the like) and to be honest is not in the current roadmap, since it has some downsides that we haven't been able to overcome.

Once the API is released (sooner than you might expect), you would be able to build custom views, but only from a subset of components that Raycast provides. Hopefully that would be enough for your requirements. In any case, I would note down your request and discuss it with the team.

Thank you for bringing this up.
