### ISSUE TITLE
recursively add script-commands from subdirectories

### ISSUE THREAD

**Issue by dannysteenman** [raycast/script-commands#655]
I got a folder with script commands, but now raycast only adds files one level deep. It would be nice to recursively add script-commands from all subdirectories e.g.

```
├── .raycast
│   ├── google-lighthouse.sh
│   ├── move-downloads-to-trash.applescript
│   ├── notes
│   │   └── append-note-from-clipboard.applescript
│   ├── open-desktop-url-from-clipboard.swift
│   ├── open-last-download.swift
│   ├── restart.applescript
│   ├── shorten-url.sh
│   ├── sleep.applescript
│   └── whatismyregion.sh
```

In the example above the script-command from the notes subdirectory is ignored when I add the .raycast directory to script-commands.

**Comment by pcjmfranken** [comment]
Raycast would start attempting to parse any utility/helper scripts people have been keeping there. The resulting uptick in parsing errors might be something to consider.

Either way it would make for a good incentive to finally clean up in there 😉

**Comment by unnamedd** [comment]
Hello @dannysteenman,

this topic popped many, many times in the Raycast Slack Community and the team always said that the lack of scanning folder and subfolders recursively is intentional, however, you have other ways to manage that.

You can:

**First,** make your voice heard in your in the community: [raycast.com/community](raycast.com/community), or

**Second,** you can use the “Send Feedback” form just accessing it directly from Raycast, or 

**Third,** you can use the [Script Commands Store ](https://www.raycast.com/tholanda/script-commands) extension to manage the Script Commands for you, and you won’t have to manage the folders and subfolders anymore.

As your request is more related to a behavior of Raycast itself and not to some Script Command, I will close this issue, however, if you have anything further to add, please, just comment in this thread.

**Comment by unnamedd** [comment]
Hello @pcjmfranken, 

this repository HAS a tool which reads all the Script Commands in this repository and does generate two different documentation files: the [README.md](https://github.com/raycast/script-commands/tree/master/commands) and also the [extensions.json](https://github.com/raycast/script-commands/blob/master/commands/extensions.json). These files are very helpful for anyone who wants to discover new Script Commands to use or create any tool (like this one, the [Script Commands Store](https://www.raycast.com/tholanda/script-commands)). What this tool (called Toolkit) does not do is any kind of evaluation or validation of the Script Commands submitted to this repository. 

There’s an idea to extend the Toolkit to validate the metatags used in the Script Commands, but this is something quite paused for now. Maybe in the future, should be reconsidered.
