### ISSUE TITLE
DeepL Web Translate script command does not pass through language correctly (Raycast Mac)

### ISSUE THREAD

**Issue by replete** [raycast/script-commands#674]
## Environment
* MacOS Monterey 12.2
* Intel Macbook Pro 13 2020 2.0ghz
* Raycast Mac 1.27.1
* DeepL 3.1.33440

## Repro

1) Install Raycast
2) Clone this git repository
3) Add `deepl` folder from `commands/script-commands/apps/` to Script Commands Directories pane in Raycast Extensions window
3) Trigger Deepl Web Translate script command from Raycast with text:`du hast` to: `english` from: `german` ![Screen Shot 2022-02-05 at 11 16 01](https://user-images.githubusercontent.com/812139/152639853-4e86ff15-01c0-42d0-ac3c-4cab9a7fd66d.png)
4) DeepL Web Translate result does not appear to have received `to` and `from` languages correctly:
![Screen Shot 2022-02-05 at 11 18 29](https://user-images.githubusercontent.com/812139/152639888-91c5f3ff-7665-427a-9ab0-00bc92966d40.png)

**Comment by replete** [comment]
@jonohewitt I see this script was written by you. Any ideas?

**Comment by jonohewitt** [comment]
Hi! This script uses shortened language codes, e.g `en` and `de` rather than full names like `english` and `german`. The language codes are defined within the script documentation comments:

```
### Language codes:

# Bulgarian: bg
# Chinese simplified: zh
# Czech: cs
# Danish: da
# Dutch: nl
# English (American and British): en
# Estonian: et
# Finnish: fi
# German: de
# Greek: el
# Hungarian: hu
# Italian: it
# Japanese: ja
# Latvian: lv
# Lithuanian: lt
# Polish: pl
# Portuguese (Brazilian and Portuguese): pt
# Romanian: ro
# Russian: ru
# Slovak: sk
# Slovenian: sl
# Spanish: es
# Swedish: sv
```

Your example should therefore be written: 

<img width="785" alt="Screenshot 2022-02-05 at 12 48 01" src="https://user-images.githubusercontent.com/47791294/152640972-7bf2f945-2ea2-4319-bbac-ee5403b97f3c.png">

Thanks for the issue, I could definitely make this clearer in the script documentation. Let me know if you're still having any problems.

**Comment by replete** [comment]
Thanks, @jonohewitt. I thought I tried this, but doing again it seemed to work. Cheers!
