### ISSUE TITLE
Using Emoji does not work properly (AppleScript)

### ISSUE THREAD

**Issue by saschaeggi** [raycast/script-commands#746]
If I use, e.g.:

`# @raycast.icon 🖼️`

This results in the AppleScript not running properly.

`Error: Process tried to run, failed `

**Comment by unnamedd** [comment]
Hi @saschaeggi, 
could you please share with us which Script Command you are trying to use (if it is in our repository) and receiving the error?

**Comment by saschaeggi** [comment]
Every AppleScript you create and use an Emoji as icon will fail with the above error message.

E.g.:

```
#!/usr/bin/osascript

# Toggle Darkmode
#
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Toggle Darkmode
# @raycast.mode silent
# @raycast.icon 🌒
# @raycast.packageName ToggleDarkmode

tell application "System Events"
	tell appearance preferences
		set dark mode to not dark mode
	end tell
end tell
```

**Comment by dehesa** [comment]
Hi @saschaeggi,

I am sorry this took so long to answer. We had a [busy week](https://twitter.com/raycastapp/status/1546518075691909124) in Raycast HQ.

You are probably having this issue because due to the file encoding. [Check this out](https://github.com/raycast/script-commands/issues/737#issuecomment-1166910422) and please let us know if that works for you.

**Comment by saschaeggi** [comment]
That worked, thank you!
