### ISSUE TITLE
[ BUG ] Clipboard History removes text formatting

### ISSUE THREAD

**Issue by ibehnam** [raycast/script-commands#755]
I've been excited to replace Maccy (clipboard manager) with Raycast's Clipboard History command. All is good except that:

1. When pasting copied text from MS Word, Raycast removes all the formatting, which is annoying.
2. It's a bit slow compared to normal paste, esp. on MS Word.

**Comment by imthath-m** [comment]
Hey @ibehnam ,

This repository is only about the script commands which users can build and share. To report feedback about the built-in commands in Raycast, please use the `Send Feedback` command.
![CleanShot 2022-08-16 at 17 08 10@2x](https://user-images.githubusercontent.com/46041492/184870534-7577d08a-018f-4e64-853e-aa65b25db27a.png)

Regarding the issues,
1. Did you try the paste formatted text action?
2. It might be because MS Word takes time to process the pasted content. Can you try with different contents and apps?

**Comment by ibehnam** [comment]
I tried "Paste Formatted Text" option but it still removed some of the formatting.  When cop-pasted normally (without using Raycast), the formatting is retained and all works fine, so I thought it can't be due to MS Word.
