### ISSUE TITLE
Issues with Script directory

### ISSUE THREAD

**Issue by anandncode** [raycast/script-commands#765]
Couple of issues WRT Script commands in MacOS.

1. The script directory is lost after a restart. Everytime the system is restarted, the directory has to be added again
2. After adding the directory, the individual scripts are not reflected immediately in Raycast. We have to open any of the script files and do minor update (any small update such as press enter key), then the individual scripts get added in Raycast

OS Details
MacOS Montery 12.5.1

**Comment by dehesa** [comment]
Hi @anandncode 

Thank you leaving your feedback and sorry you are encountering problems. Where is the folders with the scripts located? Is it in a "cloud" folder that only get synced later on? Also, what version of Raycast are you running?

**Comment by dehesa** [comment]
I will keep this open till the end of the week and if @anandncode doesn't gives us a bit more information, I will close it up. Feel free to reopen it if needed.

**Comment by anandncode** [comment]
Hi @dehesa

My apologies for not replying earlier. Somehow I missed your first reply. 

The script folder is located in my local Mac folder. It is connected to one drive that syncs the folder to cloud (but not the other way). Also the folder is made offline available.

The version I am using is 1.39.3

**Comment by dehesa** [comment]
No worries. I appreciate you got some time to write to us and sent your feedback.

Regarding your issue, we currently don't support synchronization through "cloud synchronizable" folders. This is due to some technical limitations of the file manager that we haven't had time to iron out. We may do that in the future or we might provide a synchronization service. It is still unclear what we will do. So sadly I don't have a good solution for you here. Sorry!
