### ISSUE TITLE
`python: command not found` besides having Python installed

### ISSUE THREAD

**Issue by mersocarlin** [raycast/script-commands#780]
Been trying to use [prettify-json.sh](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/prettify-json.sh) but Raycast keeps giving me that python is not installed.

### Output from my terminal

![Screen Shot 2022-10-16 at 12 00 18](https://user-images.githubusercontent.com/3759165/196031585-ab250168-6f70-4992-875b-3f25363857ed.png)

### When I manually run the `.sh` script
![Screen Shot 2022-10-16 at 12 00 43](https://user-images.githubusercontent.com/3759165/196031608-b0fa0472-eef4-467d-acd8-4c1343760cbe.png)

### Output from Raycast
![raycast](https://user-images.githubusercontent.com/3759165/196031697-15a989da-1e13-4053-a1cc-07fc38165127.jpg)

**Comment by Mattyfaz** [comment]
I had a similar issue, first ensure you have Python 3 installed rather than Python 2.
![image](https://user-images.githubusercontent.com/10377148/196074686-f1905811-5c8f-41f2-b068-dd65506d0467.png)

Then open `prettify-json.sh` and change `python` to `python3` as shown in the Screenshot below.
![image](https://user-images.githubusercontent.com/10377148/196075216-93a736c7-c48e-4d29-afb7-6fc1975f263c.png)

Now as long as you have valid json in your clipboard it should work within Raycast. 

**Bash Script**
_This is not necessary as it should now work with Raycast but just for future reference/learning,_

When running the bash script you need to pass it a parameter within quotation marks.
As an example, lets pretend your json is: `[{"key1":"value1","key2":1},{"key1":"value2","key2":2}]`

To run the bash script you would enter: `bash prettify-json.sh "[{"key1":"value1","key2":1},{"key1":"value2","key2":2}]"` which would output:
```json
[
    {
        "key1": "value1",
        "key2": 1
    },
    {
        "key1": "value2",
        "key2": 2
    }
]
```
![image](https://user-images.githubusercontent.com/10377148/196074906-a0265373-7279-4575-909c-28f880c7cd9c.png)

**Comment by mersocarlin** [comment]
@Mattyfaz 

Right, it should be python3 (aliased to run `python` commands).

But the args **are the not problem in my case** because I can see the script working in terminal (with or without args). The difference without args is that is won't give me any output, which is also correct.

And regardless of having something on the clipboard, Raycast doesn't seem to recognise the path where Python is installed.

Again, nothing is wrong with the script neither with the args (or clipboard), it is able to fail gracefully when none is provided, but instead `python is not found` from Raycast.

**Comment by Mattyfaz** [comment]
@mersocarlin 
> Right, it should be python3 (aliased to run python commands).

This is the key issue, as you can see in my screenshot in my terminal ‘python’ does alias to Python3. However when running the Raycast script that doesn’t seem to work, you have to specifically put ‘python3’ in the script file as I did in the second screenshot. Did you try that and did it work for you?

**Comment by dehesa** [comment]
I believe this issue is related to Scripts commands being executed in non-login shell as explained [here](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md#bash-profiles-and-environmental-variables).
