### ISSUE TITLE
[Question] "Always on top" functionality

### ISSUE THREAD

**Issue by FilipeMarch** [raycast/script-commands#788]
Does anyone know if there is a way of creating a `Always on top` command?
Examples on [Windows](https://learn.microsoft.com/en-us/windows/powertoys/always-on-top) or Linux
<img width="220" alt="image" src="https://user-images.githubusercontent.com/23220309/200162277-bbc0f8a2-b4dc-40d5-8720-2481966ef8b0.png">

The Window you are currently seeing will stay on top of all screens even if you click on other screens

Is it possible to do it on raycast?

**Comment by dehesa** [comment]
Hi @FilipeMarch,

As far as I know you cannot do that through a Script targeting any other window in macOS. This is not a flaw from Raycast, I just don't think it is possible in macOS.

**Comment by dehesa** [comment]
It is technically possible to make a window "float" (i.e. be on top) in an app you are compiling from the source code. It is a matter to mark a `NSWindow.level` appropriately. However, you cannot do that (at least not openly and reliably) to apps from other developers.

You may find some ways to hi-jack other devs source code, but it won't be reliable, since the developer of that app is setting the window level whenever he/she deems it necessary.
