### ISSUE TITLE
Fail to call jupyter notebook command in scirpt command

### ISSUE THREAD

**Issue by HHMathewChan** [raycast/script-commands#826]
Is that not possible to call the jupyter notebook command through using scirpt command?

## **I have try using bash:**
```
t#!/bin/bash
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title runJupyterNotebook
# @raycast.mode fullOutput
# Optional parameters:
# @raycast.icon 🤖
jupyter notebook
```

- and I have give the executable permission by `chmod +xrunjupyternotebook.sh`

## **Got the following error:**
Reason: Process terminated with status 127
Domain: scripts
Time: 10:44:58.374

**Comment by dehesa** [comment]
Hi @HHMathewChan,

That should work. You need the following requirements:
- Make sure `jupyter` and `notebook` are installed (whether through Conda or `pip`)
- Run the `jupyter notebook` command in the terminal and make sure it works.
- It is probably not working in Raycast due to the [login shell issue](https://github.com/raycast/script-commands#troubleshooting-and-faqs), you may need to add the `-l` after the shebang or just export the path that you need. For example for my case, the script looks as follow:

```bash
#!/bin/bash
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Run jupyter notebook
# @raycast.mode fullOutput
# Optional parameters:
# @raycast.icon 🤖

export PATH="$PATH:/Users/___/Library/Python/3.9/bin"
jupyter notebook
```

In any case, I don't recommend doing this, because the `jupyter notebook` is intended to live for a long time, while Raycast sessions are suppose to be short live. If you successfully execute that command in `fullOuput` mode, you won't be able to use Raycast anymore or the notebook will stop.
