### ISSUE TITLE
Disabling 'reopen windows' feature while using system restart command

### ISSUE THREAD

**Issue by rasitayaz** [raycast/script-commands#890]
When we restart the system from menu bar, we have the option to choose whether the apps should be reopen after restart or not. I don't like the alert itself much because I always keep that option disabled anyway.

<img width="529" alt="resim" src="https://github.com/raycast/script-commands/assets/45076094/f218bcdc-754b-4e26-93ee-7253bf62217a">

If we use the Raycast's 'Restart' script command, no alert window shows up, which I'm not complaining, but all the active apps before restarting reopen after restart which is not the behavior I want.

<img width="862" alt="resim" src="https://github.com/raycast/script-commands/assets/45076094/3cb4bca8-58fb-424b-8055-46de8913fbd4">

I'm not sure if this is the intended behavior, but if so, it would be nice to have the option (or another script command) for not reopening the apps after restart.

MBA M2 MacOS Sonoma 14.1.1 (23B81)

**Comment by unnamedd** [comment]
Hi @rasitayaz, thanks a lot for your very nicely detailed issue, however it was not reported on the right place. 
This repository is exclusive for Script Commands topics. 
There are two places where you can report your issue:
1 - The [Raycast Community Slack](https://raycast.com/community) 
2 - The _**Send Feedback**_ form, which can be accessed from your root search.

As you already detailed your concerns here, my suggestion for you is to submit on Send Feedback form the link for this issue here. As I already mentioned this repository is only for Script Commands, I will close it, but the link will continue to exist.
