### ISSUE TITLE
[Feature request] Reusing argument with the same name in a QuickLink

### ISSUE THREAD

**Issue by vpanichkin** [raycast/script-commands#906]
Hey guys, I would like to suggest a feature:

Using variables within quick links is great, but sometimes I must put the same variable into multiple places. My applied use case is a Jira link with the same word in **Description** and in the **Summary**

**Example**: 

Link that uses 2 time a variable **a** and once a variable **b**: 

```
google.com/variable1={a}&variable2={a}&variable3={b}
```

**Current behaviour:**
<img width="300" alt="image" src="https://github.com/raycast/script-commands/assets/16993030/848c53cf-af62-44a4-b788-9b636ce09e42">

**Expected behaviour**
<img width="221" alt="image" src="https://github.com/raycast/script-commands/assets/16993030/13d5994e-6b55-40a1-8907-64a9cf067d78">

**Comment by unnamedd** [comment]
Hi @vpanichkin,
even though your request is related to Script Commands, it is not exactly about a Script Command, but a feature on Raycast itself, because of that, I highly recommend you to use the `Send Feedback` form (you can find it just typing it in the root search) or using our Slack Community (https://raycast.com/community), the channel will be #suggestions.

I'm closing this issue, but you can continue to comment on top of it if you have any further question.
