### ISSUE TITLE
[Feature] Disable certain applications for custom scripts.

### ISSUE THREAD

**Issue by rapatel0** [raycast/script-commands#918]
As a user there are some scripts that should only be invoked for certain applications.  Ideally we can specify the disabled applications in raycast to ensure that commands / hotkeys don't conflict with application shortcuts. This already exists for hotkeys in several raycast plugins. 

Example: 
The menu hot key  (CMD-SHIFT-P) is disabled for applications Cursor, and Obsidian. 

<img width="1024" alt="image" src="https://github.com/raycast/script-commands/assets/18704704/7cc3400d-5b5f-4cf0-818c-e626781303ae">

## Implementation Suggestions
- Parameter in script metadata that controls ignored applications.  Example`@raycast.ignoredApplicatons Cursor, Obsidian`
- UI based solution similar to search menubar

**Comment by unnamedd** [comment]
Hi @rapatel0,
based on your description, you issue seems to be related to a Feature Request for Raycast itself. To do that, you should open the Send Feedback form directly from your root search on Raycast and submit there. The second option is to bring it to our Slack Community: raycast.com/community.

I am going to close this issue here, but if you need anything else, please, just write another comment.
