### ISSUE TITLE
"Script Commands" Extension Not Being Displayed

### ISSUE THREAD

**Issue by Joprey** [raycast/script-commands#923]

**Comment by Joprey** [comment]
Hello,

I've encountered an issue where my extension titled "Script Commands" is not being displayed as expected. I have followed the standard procedures for installing and activating extensions within the environment, but for some reason, this particular extension remains invisible or inaccessible in the interface.

**Comment by unnamedd** [comment]
> I've encountered an issue where my extension titled "Script Commands" is not being displayed as expected.

Hi 👋
may I ask exactly what you are trying to refer to? You are trying to use an extension called Script Commands or are you trying to install a Script Command itself and facing problems during your process. 

> this particular extension remains invisible or inaccessible in the interface.
To an extension be invisible in the root search, it need to be disabled on Raycast Settings. Is this that case?

I am not really sure if you are facing problems with Script Commands or Extensions. In any case, I highly recommend you to use our Slack Community for it since your issue doesn't seem to be exactly connected to the development of Script Commands.

I am closing this issue, but feel free to write any other comment in case in you further assistance.

Slack Community: raycast.com/community 
Channel: #script-commands or #extensions
